### ISSUE TITLE
Feldcroft collection chest #3

### ISSUE THREAD

**Issue by Thortok** [Malin001/Legilimens-Hogwarts-Legacy-cpp#4]
collection chest #1 and #3 have the same timestamp

![image](https://user-images.githubusercontent.com/14281289/223793501-6d377998-5024-4a64-8dbd-ef1a00c1f894.png)

**Comment by Thortok** [comment]
Actually now that I'm looking through it there's a lot of them with duplicate timestamps. Collection chests 10 and 9 are even out of order.

**Comment by Malin001** [comment]
Right now, all of my timestamps are directly from the video desciption, which is a bit of a problem when the video creator groups multiple collectibles into one timestamp. In the example you gave, it's from the timestamp "01:53 - Collection Chest 1-3/22", which has three collections chests for a single timestamp.

In order to get the exact timestamps for everything, I have to go through each video and manually find the timestamps, which, unfortunately, takes time. It's on my todo list for the next update though, along with the filter for which items are obtainable.

**Comment by Thortok** [comment]
I noticed after posting that the videos were by someone else who is less efficient at getting straight to the collectible and solving puzzles quickly and optimally. XD

I can help with manually finding the timestamps but I don't know which chest is coded as which in the savefile and such.

If there's any way I can assist, let me know.

**Comment by Malin001** [comment]
Turns out there were only a few regions that had the duplicate timestamps, so it was actually pretty easy to find and update them all. The timestamps should be up to date as of v0.2.4
